# Ép server chấp nhận tài khoản crack từ TLauncher
online-mode=false

# CẤU HÌNH TÊN SERVER VÀ MOTD (DÒNG MÔ TẢ)
server-name=VnMine
motd=§aThế giới tu tiên! §f[§bOnline 24/7§f]

# Giữ nguyên cổng port nội bộ cho Minecraft
server-port=25565
server-ip=0.0.0.0

# ĐÃ CẬP NHẬT: Tăng tầm nhìn và giả lập thực thể xa hơn
view-distance=12
simulation-distance=10

# Các cấu hình tối ưu hiệu năng cho Hugging Face Space
max-players=10
allow-flight=true

level-seed=4060072015345129782